version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: db_test # main dev database
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      retries: 5

  app:
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV}
        - BLAND_AI_API_KEY=${BLAND_AI_API_KEY}
        - BLAND_AI_DEVELOPMENT_API_KEY=${BLAND_AI_DEVELOPMENT_API_KEY}
        - BLAND_AI_WEBHOOK_SECRET=${BLAND_AI_WEBHOOK_SECRET}
        - BLAND_AI_FROM_NUMBER=${BLAND_AI_FROM_NUMBER}
        - BLAND_AI_DEVELOPMENT_FROM_NUMBER=${BLAND_AI_DEVELOPMENT_FROM_NUMBER}
        - BLAND_AI_TWILIO_ENCRYPTED_KEY=${BLAND_AI_TWILIO_ENCRYPTED_KEY}
        - BLAND_AI_DEVELOPMENT_TWILIO_ENCRYPTED_KEY=${BLAND_AI_DEVELOPMENT_TWILIO_ENCRYPTED_KEY}
        - DATABASE_URL=${DATABASE_URL}
        - SHADOW_DATABASE_URL=${SHADOW_DATABASE_URL}
    container_name: care-activation-app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=mysql://root:dev@mysql:3306/db_test
      - BLAND_AI_API_KEY=${BLAND_AI_API_KEY}
      - BLAND_AI_DEVELOPMENT_API_KEY=${BLAND_AI_DEVELOPMENT_API_KEY}
      - BLAND_AI_WEBHOOK_SECRET=${BLAND_AI_WEBHOOK_SECRET}
      - BLAND_AI_FROM_NUMBER=${BLAND_AI_FROM_NUMBER}
      - BLAND_AI_DEVELOPMENT_FROM_NUMBER=${BLAND_AI_DEVELOPMENT_FROM_NUMBER}
      - BLAND_AI_TWILIO_ENCRYPTED_KEY=${BLAND_AI_TWILIO_ENCRYPTED_KEY}
      - BLAND_AI_DEVELOPMENT_TWILIO_ENCRYPTED_KEY=${BLAND_AI_DEVELOPMENT_TWILIO_ENCRYPTED_KEY}
      - PORT=3000
      - NODE_ENV=${NODE_ENV}
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_AGENT_PORT=8126

    depends_on:
      mysql:
        condition: service_healthy

    volumes:
      - .:/app
      - /app/node_modules

  datadog-agent:
    image: gcr.io/datadoghq/agent:latest
    environment:
      - DD_API_KEY=${DATADOG_API_KEY}
      - DD_SITE=us3.datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_APM_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_LOGS_JSON=true
      - DD_CONTAINER_EXCLUDE=image:datadog/agent:*
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /proc/:/host/proc/:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro

volumes:
  mysql-data:
