version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: db_test # main dev database
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      retries: 5

  app:
    build: .
    container_name: care-activation-app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=mysql://root:dev@mysql:3306/db_test
      - BLAND_AI_API_KEY=${BLAND_AI_API_KEY}
      - PORT=3000
      - NODE_ENV=${NODE_ENV}

    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules

  datadog-agent:
    image: gcr.io/datadoghq/agent:latest
    environment:
      - DD_API_KEY=${DATADOG_API_KEY}
      - DD_SITE=us3.datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_APM_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_LOGS_JSON=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  mysql-data:
