name: Build and Push Release to ECR

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::417107812602:role/care-activation-dev-ecr-push-role
          aws-region: <AWS_REGION>

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Release Docker image
        run: |
          VERSION_TAG=${GITHUB_REF_NAME}   # e.g. v1.2.3 or release/1.0
          SANITIZED_TAG=$(echo $VERSION_TAG | sed 's#[^a-zA-Z0-9._-]#-#g')

          IMAGE_TAG=v-care-activation-commit-${SANITIZED_TAG}
          REPO_URI=${{ steps.login-ecr.outputs.registry }}/care-activation

          docker build -t $REPO_URI:$IMAGE_TAG .
          docker push $REPO_URI:$IMAGE_TAG

          # Optional stable tag
          docker tag $REPO_URI:$IMAGE_TAG $REPO_URI:stable
          docker push $REPO_URI:stable
